# Generated by Django 4.1 on 2023-02-23 21:49

import backbone.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('A', 'Available'), ('S', 'Sold')], max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('ELEC', 'Electronics'), ('FURN', 'Furniture'), ('CLOT', 'Clothing'), ('BOOK', 'Books'), ('SPOR', 'Sports'), ('COLL', 'Collections'), ('INTR', 'Music Instruments'), ('ACCE', 'Accessories'), ('ACCE', 'Home Appliances')], max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=backbone.models.get_url)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.product')),
            ],
        ),
    ]
