# Generated by Django 4.1.6 on 2023-03-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backbone", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="password",
            name="token",
            field=models.FileField(max_length=255, null=True, upload_to=""),
        ),
    ]
