# Generated by Django 4.1 on 2023-03-28 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0003_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='Used', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELEC', 'Electronics'), ('FURN', 'Furniture'), ('CLOT', 'Clothing'), ('BOOK', 'Books'), ('SPOR', 'Sports'), ('COLL', 'Collectibles'), ('INTR', 'Music Instruments'), ('ACCE', 'Accessories'), ('ACCE', 'Home Appliances')], max_length=4),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='backbone.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.product')),
                ('seller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='backbone.user')),
            ],
        ),
    ]
