# Generated by Django 4.1 on 2023-03-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0004_product_quality_alter_product_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('V', 'Valid'), ('C', 'Cancelled')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELEC', 'Electronics'), ('FURN', 'Furniture'), ('CLOT', 'Clothing'), ('BOOK', 'Books'), ('SPOR', 'Sports'), ('COLL', 'Collectibles'), ('INTR', 'Instruments'), ('ACCE', 'Accessories'), ('ACCE', 'Appliances')], max_length=4),
        ),
    ]
